<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="ja" sourcelanguage="en">
  <context>
    <name>@default</name>
    <message>
      <source>MEN_EXPORTSTL</source>
      <translation>STLエクスポート</translation>
    </message>
    <message>
      <source>TOP_EXPORTSTL</source>
      <translation>STLエクスポート</translation>
    </message>
    <message>
      <source>STB_EXPORTSTL</source>
      <translation>STLエクスポート</translation>
    </message>
    <message>
      <source>MEN_IMPORTSTL</source>
      <translation>STLインポート</translation>
    </message>
    <message>
      <source>TOP_IMPORTSTL</source>
      <translation>STLインポート</translation>
    </message>
    <message>
      <source>STB_IMPORTSTL</source>
      <translation>STLインポート</translation>
    </message>
  </context>
  <context>
    <name>STLPlugin_GUI</name>
    <message>
      <source>STL_FILES</source>
      <translation>STLファイル</translation>
    </message>
    <message>
      <source>EXPORT_TITLE</source>
      <translation>STLエクスポート</translation>
    </message>
    <message>
      <source>IMPORT_TITLE</source>
      <translation>STLインポート</translation>
    </message>
  </context>
  <context>
    <name>STLPlugin_ExportDlg</name>
    <message>
      <source>ASCII</source>
      <translation>アスキーテキスト</translation>
    </message>
    <message>
      <source>RELATIVE</source>
      <translation type="unfinished">Relative</translation>
    </message>
    <message>
      <source>DEFLECTION</source>
      <translation type="unfinished">Deflection</translation>
    </message>
  </context>
</TS>
