<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="ja" sourcelanguage="en">
  <context>
    <name>@default</name>
    <message>
      <source>MEN_EXPORTIGES</source>
      <translation>IGESエクスポート</translation>
    </message>
    <message>
      <source>TOP_EXPORTIGES</source>
      <translation>IGESエクスポート</translation>
    </message>
    <message>
      <source>STB_EXPORTIGES</source>
      <translation>IGESエクスポート</translation>
    </message>
    <message>
      <source>MEN_IMPORTIGES</source>
      <translation>IGESインポート</translation>
    </message>
    <message>
      <source>TOP_IMPORTIGES</source>
      <translation>IGESインポート</translation>
    </message>
    <message>
      <source>STB_IMPORTIGES</source>
      <translation>IGESインポート</translation>
    </message>
  </context>
  <context>
    <name>IGESPlugin_GUI</name>
    <message>
      <source>IGES_FILES</source>
      <translation>IGES ファイル ( *.iges *.igs )</translation>
    </message>
    <message>
      <source>EXPORT_TITLE</source>
      <translation>IGESエクスポート</translation>
    </message>
    <message>
      <source>IMPORT_TITLE</source>
      <translation>IGESインポート</translation>
    </message>
    <message>
      <source>SCALE_DIMENSIONS</source>
      <translation>インポートしたファイルの単位をミリメートルからメートルに変換しますか？いいえを選んだ場合、メートル単位として解釈します。</translation>
    </message>
  </context>
  <context>
    <name>IGESPlugin_ExportDlg</name>
    <message>
      <source>IGES_VERSION</source>
      <translation>IGESバージョン</translation>
    </message>
  </context>
</TS>
