// File generated by CPPExt (Enum)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _GEOMAlgo_KindOfName_HeaderFile
#define _GEOMAlgo_KindOfName_HeaderFile


enum GEOMAlgo_KindOfName { 
 GEOMAlgo_KN_UNKNOWN,
GEOMAlgo_KN_SPHERE,
GEOMAlgo_KN_CYLINDER,
GEOMAlgo_KN_TORUS,
GEOMAlgo_KN_CONE,
GEOMAlgo_KN_ELLIPSE,
GEOMAlgo_KN_CIRCLE,
GEOMAlgo_KN_PLANE,
GEOMAlgo_KN_LINE,
GEOMAlgo_KN_BOX,
GEOMAlgo_KN_SEGMENT,
GEOMAlgo_KN_ARCCIRCLE,
GEOMAlgo_KN_POLYGON,
GEOMAlgo_KN_POLYHEDRON,
GEOMAlgo_KN_DISKCIRCLE,
GEOMAlgo_KN_DISKELLIPSE,
GEOMAlgo_KN_RECTANGLE,
GEOMAlgo_KN_TRIANGLE,
GEOMAlgo_KN_QUADRANGLE,
GEOMAlgo_KN_ARCELLIPSE
};


#ifndef _Standard_PrimitiveTypes_HeaderFile
#include <Standard_PrimitiveTypes.hxx>
#endif

#endif
