<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="ja" sourcelanguage="en">
  <context>
    <name>@default</name>
    <message>
      <source>GEOM_ADVANCED</source>
      <translation>高度な形状: タイプ %1</translation>
    </message>
    <message>
      <source>GEOM_ADVANCED_201</source>
      <translation>T型パイプ</translation>
    </message>
    <message>
      <source>GEOM_ADVANCED_202</source>
      <translation>カット済みディスク</translation>
    </message>
    <message>
      <source>GEOM_ADVANCED_203</source>
      <translation>カット シリンダー</translation>
    </message>
    <message>
      <source>GEOM_DIVIDEDDISK</source>
      <translation>分割ディスク</translation>
    </message>
    <message>
      <source>GEOM_DIVIDEDDISK_TITLE</source>
      <translation>分割ディスクの構築</translation>
    </message>
    <message>
      <source>GEOM_DIVIDEDCYLINDER</source>
      <translation>分割シリンダー</translation>
    </message>
    <message>
      <source>GEOM_DIVIDEDCYLINDER_TITLE</source>
      <translation>分割シリンダの構築</translation>
    </message>
    <message>
      <source>MEN_DIVIDEDCYLINDER</source>
      <translation>分割シリンダ</translation>
    </message>
    <message>
      <source>TOP_DIVIDEDCYLINDER</source>
      <translation>分割シリンダ</translation>
    </message>
    <message>
      <source>STB_DIVIDEDCYLINDER</source>
      <translation>分割シリンダ</translation>
    </message>
    <message>
      <source>MEN_DIVIDEDDISK</source>
      <translation>分割ディスク</translation>
    </message>
    <message>
      <source>TOP_DIVIDEDDISK</source>
      <translation>分割ディスク</translation>
    </message>
    <message>
      <source>STB_DIVIDEDDISK</source>
      <translation>分割ディスク</translation>
    </message>
    <message>
      <source>TOP_PIPETSHAPE</source>
      <translation>T型パイプを作成</translation>
    </message>
    <message>
      <source>MEN_PIPETSHAPE</source>
      <translation>T型パイプを作成</translation>
    </message>
    <message>
      <source>STB_PIPETSHAPE</source>
      <translation>T型パイプを作成</translation>
    </message>
    <message>
      <source>TOP_SMOOTHINGSURFACE</source>
      <translation>表面のスムージング</translation>
    </message>
    <message>
      <source>MEN_SMOOTHINGSURFACE</source>
      <translation>表面の平滑化</translation>
    </message>
    <message>
      <source>STB_SMOOTHINGSURFACE</source>
      <translation>表面のスムージング</translation>
    </message>
    <message>
      <source>HALF_LENGTH_MAIN_PIPE</source>
      <translation>半分の長さのパイプを作成</translation>
    </message>
    <message>
      <source>HALF_LENGTH_INCIDENT_PIPE</source>
      <translation>入射管長さ半分</translation>
    </message>
    <message>
      <source>CIRCULAR_QUARTER_PIPE</source>
      <translation>パイプの１/4形状</translation>
    </message>
    <message>
      <source>THICKNESS</source>
      <translation>厚み</translation>
    </message>
    <message>
      <source>FLANGE</source>
      <translation>フランジ</translation>
    </message>
    <message>
      <source>CHAMFER_OR_FILLET</source>
      <translation>面取り 又は フィレット</translation>
    </message>
    <message>
      <source>CHAMFER</source>
      <translation>面取り</translation>
    </message>
    <message>
      <source>FILLET</source>
      <translation>フィレット</translation>
    </message>
    <message>
      <source>JUNCTION_FACE_1</source>
      <translation>継手面1</translation>
    </message>
    <message>
      <source>JUNCTION_FACE_2</source>
      <translation>継手面2</translation>
    </message>
    <message>
      <source>JUNCTION_FACE_3</source>
      <translation>継手面3</translation>
    </message>
    <message>
      <source>INTERNAL_FACES</source>
      <translation>内部の面</translation>
    </message>
  </context>
  <context>
    <name>AdvancedGUI_PipeTShapeDlg</name>
    <message>
      <source>GEOM_PIPE_TSHAPE_TITLE</source>
      <translation>T型パイプの作成</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE</source>
      <translation>T型パイプ</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_MPIPE</source>
      <translation>メインパイプ</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_R</source>
      <translation>半径</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_W</source>
      <translation>幅</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_L</source>
      <translation>半分の長さ</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_IPIPE</source>
      <translation>付随パイプ</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_CHAMFER</source>
      <translation>面取り</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_CHAMFER_H</source>
      <translation>高さ</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_CHAMFER_W</source>
      <translation>幅</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_FILLET</source>
      <translation>フィレット</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_HEX</source>
      <translation>六面体メッシュの準備</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_POSITION</source>
      <translation>位置を設定</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_POSITION_P1</source>
      <translation>接続部 P1</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_POSITION_P2</source>
      <translation>接続部 P2</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_POSITION_P3</source>
      <translation>接続部 P3</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_POSITION_LBL_L1</source>
      <translation>T型パイプの位置 L1</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_POSITION_LBL_L2</source>
      <translation>T型パイプの位置 L2</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_LEFT_TR</source>
      <translation>左側肉厚変更</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_RIGHT_TR</source>
      <translation>右側肉厚変更</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_INCI_TR</source>
      <translation>付随パイプ肉厚変更</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_TR_R</source>
      <translation>半径 (r%1)</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_TR_W</source>
      <translation>厚み (w%1)</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_TR_L_TRANS</source>
      <translation>拡張部長さ (ltrans %1)</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_TR_L_THIN</source>
      <translation>接続部長さ (lthin %1)</translation>
    </message>
    <message>
      <source>GEOM_PIPETSHAPE_GROUPMAIN</source>
      <translation>メインの設定</translation>
    </message>
    <message>
      <source>GEOM_PIPETSHAPE_GROUPREDUCT</source>
      <translation>接続部詳細設定</translation>
    </message>
    <message>
      <source>GEOM_PIPETSHAPE_GROUPPOS</source>
      <translation>位置による設定</translation>
    </message>
    <message>
      <source>GEOM_PIPETSHAPE_ERR_EQUAL_RADII_L</source>
      <translation>メインパイプの半径は、左側薄型化（rL）と等しくすることはできません！</translation>
    </message>
    <message>
      <source>GEOM_PIPETSHAPE_ERR_EQUAL_EXT_RADII_L</source>
      <translation>メインパイプの外半径（半径+幅）は、左側薄型化外半径（rL+wL）と等しくすることはできません！</translation>
    </message>
    <message>
      <source>GEOM_PIPETSHAPE_ERR_EQUAL_RADII_R</source>
      <translation>メインパイプの半径は、右側薄型化半径（rR）と同じにすることはできません！</translation>
    </message>
    <message>
      <source>GEOM_PIPETSHAPE_ERR_EQUAL_EXT_RADII_R</source>
      <translation>メインパイプの外半径（半径+幅）は、右側薄型化外半径（rR+wR）と等しくすることはできません！</translation>
    </message>
    <message>
      <source>GEOM_PIPETSHAPE_ERR_EQUAL_RADII_I</source>
      <translation>インシデントパイプの半径は、インシデントパイプ薄肉化半径（rl）と等しくすることはできません！</translation>
    </message>
    <message>
      <source>GEOM_PIPETSHAPE_ERR_EQUAL_EXT_RADII_I</source>
      <translation>インシデントパイプの外半径（半径+厚さ）は、インシデントパイプの薄肉化外半径（rI+wI）と等しくすることはできません！</translation>
    </message>
  </context>
  <context>
    <name>AdvancedGUI_SmoothingSurfaceDlg</name>
    <message>
      <source>GEOM_SMOOTHINGSURFACE_TITLE</source>
      <translation>滑らかな表面の構造</translation>
    </message>
    <message>
      <source>GEOM_SMOOTHINGSURFACE</source>
      <translation>表面 lissee</translation>
    </message>
    <message>
      <source>GEOM_SMOOTHINGSURFACE_RESULT</source>
      <translation>結果の名前</translation>
    </message>
    <message>
      <source>GEOM_SMOOTHINGSURFACE_ARG</source>
      <translation>節点</translation>
    </message>
    <message>
      <source>GEOM_SMOOTHINGSURFACE_ARG_POINTS</source>
      <translation>ポイント</translation>
    </message>
    <message>
      <source>GEOM_SMOOTHINGSURFACE_ARG_NB_MAX</source>
      <translation>ベジェパッチの最大数&lt;</translation>
    </message>
    <message>
      <source>GEOM_SMOOTHINGSURFACE_ARG_DEG_MAX</source>
      <translation>Bスプライン面の最大自由度</translation>
    </message>
    <message>
      <source>GEOM_SMOOTHINGSURFACE_ARG_D_MAX</source>
      <translation>初期近似の３次元公差</translation>
    </message>
    <message>
      <source>GEOM_SMOOTHINGSURFACE_NO_POINTS</source>
      <translation>点が選択されていない</translation>
    </message>
  </context>
</TS>
