<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS>
  <context>
    <name>@default</name>
    <message>
      <source>GEOM_ADVANCED</source>
      <translation>GEOM_ADVANCED</translation>
    </message>
    <message>
      <source>GEOM_ADVANCED_201</source>
      <translation>GEOM_ADVANCED_201</translation>
    </message>
    <message>
      <source>GEOM_ADVANCED_202</source>
      <translation>GEOM_ADVANCED_202</translation>
    </message>
    <message>
      <source>GEOM_ADVANCED_203</source>
      <translation>GEOM_ADVANCED_203</translation>
    </message>
    <message>
      <source>GEOM_DIVIDEDDISK</source>
      <translation>GEOM_DIVIDEDDISK</translation>
    </message>
    <message>
      <source>GEOM_DIVIDEDDISK_TITLE</source>
      <translation>GEOM_DIVIDEDDISK_TITLE</translation>
    </message>
    <message>
      <source>GEOM_DIVIDEDCYLINDER</source>
      <translation>GEOM_DIVIDEDCYLINDER</translation>
    </message>
    <message>
      <source>GEOM_DIVIDEDCYLINDER_TITLE</source>
      <translation>GEOM_DIVIDEDCYLINDER_TITLE</translation>
    </message>
    <message>
      <source>MEN_DIVIDEDCYLINDER</source>
      <translation>MEN_DIVIDEDCYLINDER</translation>
    </message>
    <message>
      <source>TOP_DIVIDEDCYLINDER</source>
      <translation>TOP_DIVIDEDCYLINDER</translation>
    </message>
    <message>
      <source>STB_DIVIDEDCYLINDER</source>
      <translation>STB_DIVIDEDCYLINDER</translation>
    </message>
    <message>
      <source>MEN_DIVIDEDDISK</source>
      <translation>MEN_DIVIDEDDISK</translation>
    </message>
    <message>
      <source>TOP_DIVIDEDDISK</source>
      <translation>TOP_DIVIDEDDISK</translation>
    </message>
    <message>
      <source>STB_DIVIDEDDISK</source>
      <translation>STB_DIVIDEDDISK</translation>
    </message>
    <message>
      <source>TOP_PIPETSHAPE</source>
      <translation>TOP_PIPETSHAPE</translation>
    </message>
    <message>
      <source>MEN_PIPETSHAPE</source>
      <translation>MEN_PIPETSHAPE</translation>
    </message>
    <message>
      <source>STB_PIPETSHAPE</source>
      <translation>STB_PIPETSHAPE</translation>
    </message>
    <message>
      <source>TOP_SMOOTHINGSURFACE</source>
      <translation>TOP_SMOOTHINGSURFACE</translation>
    </message>
    <message>
      <source>MEN_SMOOTHINGSURFACE</source>
      <translation>MEN_SMOOTHINGSURFACE</translation>
    </message>
    <message>
      <source>STB_SMOOTHINGSURFACE</source>
      <translation>STB_SMOOTHINGSURFACE</translation>
    </message>
    <message>
      <source>HALF_LENGTH_MAIN_PIPE</source>
      <translation>HALF_LENGTH_MAIN_PIPE</translation>
    </message>
    <message>
      <source>HALF_LENGTH_INCIDENT_PIPE</source>
      <translation>HALF_LENGTH_INCIDENT_PIPE</translation>
    </message>
    <message>
      <source>CIRCULAR_QUARTER_PIPE</source>
      <translation>CIRCULAR_QUARTER_PIPE</translation>
    </message>
    <message>
      <source>THICKNESS</source>
      <translation>THICKNESS</translation>
    </message>
    <message>
      <source>FLANGE</source>
      <translation>FLANGE</translation>
    </message>
    <message>
      <source>CHAMFER_OR_FILLET</source>
      <translation>CHAMFER_OR_FILLET</translation>
    </message>
    <message>
      <source>CHAMFER</source>
      <translation>CHAMFER</translation>
    </message>
    <message>
      <source>FILLET</source>
      <translation>FILLET</translation>
    </message>
    <message>
      <source>JUNCTION_FACE_1</source>
      <translation>JUNCTION_FACE_1</translation>
    </message>
    <message>
      <source>JUNCTION_FACE_2</source>
      <translation>JUNCTION_FACE_2</translation>
    </message>
    <message>
      <source>JUNCTION_FACE_3</source>
      <translation>JUNCTION_FACE_3</translation>
    </message>
    <message>
      <source>INTERNAL_FACES</source>
      <translation>INTERNAL_FACES</translation>
    </message>
  </context>
  <context>
    <name>AdvancedGUI_PipeTShapeDlg</name>
    <message>
      <source>GEOM_PIPE_TSHAPE_TITLE</source>
      <translation>GEOM_PIPE_TSHAPE_TITLE</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE</source>
      <translation>GEOM_PIPE_TSHAPE</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_MPIPE</source>
      <translation>GEOM_PIPE_TSHAPE_MPIPE</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_R</source>
      <translation>GEOM_PIPE_TSHAPE_R</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_W</source>
      <translation>GEOM_PIPE_TSHAPE_W</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_L</source>
      <translation>GEOM_PIPE_TSHAPE_L</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_IPIPE</source>
      <translation>GEOM_PIPE_TSHAPE_IPIPE</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_CHAMFER</source>
      <translation>GEOM_PIPE_TSHAPE_CHAMFER</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_CHAMFER_H</source>
      <translation>GEOM_PIPE_TSHAPE_CHAMFER_H</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_CHAMFER_W</source>
      <translation>GEOM_PIPE_TSHAPE_CHAMFER_W</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_FILLET</source>
      <translation>GEOM_PIPE_TSHAPE_FILLET</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_HEX</source>
      <translation>GEOM_PIPE_TSHAPE_HEX</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_POSITION</source>
      <translation>GEOM_PIPE_TSHAPE_POSITION</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_POSITION_P1</source>
      <translation>GEOM_PIPE_TSHAPE_POSITION_P1</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_POSITION_P2</source>
      <translation>GEOM_PIPE_TSHAPE_POSITION_P2</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_POSITION_P3</source>
      <translation>GEOM_PIPE_TSHAPE_POSITION_P3</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_POSITION_LBL_L1</source>
      <translation>GEOM_PIPE_TSHAPE_POSITION_LBL_L1</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_POSITION_LBL_L2</source>
      <translation>GEOM_PIPE_TSHAPE_POSITION_LBL_L2</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_LEFT_TR</source>
      <translation>GEOM_PIPE_TSHAPE_LEFT_TR</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_RIGHT_TR</source>
      <translation>GEOM_PIPE_TSHAPE_RIGHT_TR</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_INCI_TR</source>
      <translation>GEOM_PIPE_TSHAPE_INCI_TR</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_TR_R</source>
      <translation>GEOM_PIPE_TSHAPE_TR_R</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_TR_W</source>
      <translation>GEOM_PIPE_TSHAPE_TR_W</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_TR_L_TRANS</source>
      <translation>GEOM_PIPE_TSHAPE_TR_L_TRANS</translation>
    </message>
    <message>
      <source>GEOM_PIPE_TSHAPE_TR_L_THIN</source>
      <translation>GEOM_PIPE_TSHAPE_TR_L_THIN</translation>
    </message>
    <message>
      <source>GEOM_PIPETSHAPE_GROUPMAIN</source>
      <translation>GEOM_PIPETSHAPE_GROUPMAIN</translation>
    </message>
    <message>
      <source>GEOM_PIPETSHAPE_GROUPREDUCT</source>
      <translation>GEOM_PIPETSHAPE_GROUPREDUCT</translation>
    </message>
    <message>
      <source>GEOM_PIPETSHAPE_GROUPPOS</source>
      <translation>GEOM_PIPETSHAPE_GROUPPOS</translation>
    </message>
  </context>
  <context>
    <name>AdvancedGUI_SmoothingSurfaceDlg</name>
    <message>
      <source>GEOM_SMOOTHINGSURFACE_TITLE</source>
      <translation>GEOM_SMOOTHINGSURFACE_TITLE</translation>
    </message>
    <message>
      <source>GEOM_SMOOTHINGSURFACE</source>
      <translation>GEOM_SMOOTHINGSURFACE</translation>
    </message>
    <message>
      <source>GEOM_SMOOTHINGSURFACE_RESULT</source>
      <translation>GEOM_SMOOTHINGSURFACE_RESULT</translation>
    </message>
    <message>
      <source>GEOM_SMOOTHINGSURFACE_ARG</source>
      <translation>GEOM_SMOOTHINGSURFACE_ARG</translation>
    </message>
    <message>
      <source>GEOM_SMOOTHINGSURFACE_ARG_POINTS</source>
      <translation>GEOM_SMOOTHINGSURFACE_ARG_POINTS</translation>
    </message>
  </context>
</TS>
