<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="en_US">
    <context>
        <name>@default</name>
        <message>
            <source>ICON_CC_ARROW_UP</source>
            <translation>arrow_up.png</translation>
        </message>
        <message>
            <source>ICON_CC_ARROW_DOWN</source>
            <translation>arrow_down.png</translation>
        </message>
        <message>
            <source>ICON_CC_CLOSED_POLYLINE</source>
            <translation>closedpolyline.png</translation>
        </message>
        <message>
            <source>ICON_CC_CLOSED_SPLINE</source>
            <translation>closedspline.png</translation>
        </message>
        <message>
            <source>ICON_CC_DELETE</source>
            <translation>delete.png</translation>
        </message>
        <message>
            <source>ICON_CC_JOIN</source>
            <translation>join2.png</translation>
        </message>
        <message>
            <source>ICON_CC_BRING_TOGETHER</source>
            <translation>bringTogether.png</translation>
        </message>
        <message>
            <source>ICON_CC_NEW_POINT</source>
            <translation>new_point.png</translation>
        </message>
        <message>
            <source>ICON_CC_NEW_SECTION</source>
            <translation>new_section.png</translation>
        </message>
        <message>
            <source>ICON_CC_EDIT_POINTS</source>
            <translation>edit_points.png</translation>
        </message>
        <message>
            <source>ICON_CC_POINT</source>
            <translation>point2.png</translation>
        </message>
        <message>
            <source>ICON_CC_POLYLINE</source>
            <translation>polyline.png</translation>
        </message>
        <message>
            <source>ICON_CC_REDO</source>
            <translation>redo.png</translation>
        </message>
        <message>
            <source>ICON_CC_SPLINE</source>
            <translation>spline.png</translation>
        </message>
        <message>
            <source>ICON_CC_UNDO</source>
            <translation>undo.png</translation>
        </message>
        <message>
            <source>ICON_FOLDER</source>
            <translation>folder.png</translation>
        </message>
        <message>
            <source>ICON_DLG_ADD_POINT_ON_EDGE</source>
            <translation>pointonedge.png</translation>
        </message>
        <message>
            <source>ICON_DLG_ARC</source>
            <translation>arc.png</translation>
        </message>
        <message>
            <source>ICON_DLG_ARCHIMEDE</source>
            <translation>archimede.png</translation>
        </message>
        <message>
            <source>ICON_DLG_ARC_CENTER</source>
            <translation>arccenter.png</translation>
        </message>
        <message>
            <source>ICON_DLG_ARC_OF_ELLIPSE</source>
            <translation>arcofellipse.png</translation>
        </message>
        <message>
            <source>ICON_DLG_BASICPROPERTIES</source>
            <translation>basicproperties.png</translation>
        </message>
        <message>
            <source>ICON_DLG_BEZIER</source>
            <translation>bezier.png</translation>
        </message>
        <message>
            <source>ICON_DLG_BLOCK_2F</source>
            <translation>block_2f.png</translation>
        </message>
        <message>
            <source>ICON_DLG_BLOCK_6F</source>
            <translation>block_6f.png</translation>
        </message>
        <message>
            <source>ICON_DLG_BLOCK_EXPLODE</source>
            <translation>subblock.png</translation>
        </message>
        <message>
            <source>ICON_DLG_BLOCK_MULTITRSF_DOUBLE</source>
            <translation>block_multitrsf_double.png</translation>
        </message>
        <message>
            <source>ICON_DLG_BLOCK_MULTITRSF_SIMPLE</source>
            <translation>block_multitrsf_simple.png</translation>
        </message>
        <message>
            <source>ICON_DLG_BOUNDING_BOX</source>
            <translation>bounding.png</translation>
        </message>
        <message>
            <source>ICON_DLG_BOX_2P</source>
            <translation>box2points.png</translation>
        </message>
        <message>
            <source>ICON_DLG_BOX_DXYZ</source>
            <translation>boxdxyz.png</translation>
        </message>
        <message>
            <source>ICON_DLG_BUILD_COMPOUND</source>
            <translation>build_compound.png</translation>
        </message>
	<message>
            <source>ICON_DLG_DISK</source>
            <translation>disk.png</translation>
        </message>
	<message>
            <source>ICON_DLG_DISK_PNT_VEC_R</source>
            <translation>disk_pntvecr.png</translation>
        </message>
	<message>
            <source>ICON_DLG_DISK_THREE_POINTS</source>
            <translation>disk3points.png</translation>
        </message>
	<message>
            <source>ICON_DLG_DISK_R</source>
            <translation>disk_r.png</translation>
        </message>
        <message>
            <source>ICON_DLG_BUILD_EDGE</source>
            <translation>build_edge.png</translation>
        </message>
        <message>
            <source>ICON_DLG_BUILD_EDGE_WIRE</source>
            <translation>build_edge_wire.png</translation>
        </message>
        <message>
            <source>ICON_DLG_BUILD_EDGE_CURVE</source>
            <translation>build_edge_curve.png</translation>
        </message>
        <message>
            <source>ICON_DLG_BUILD_FACE</source>
            <translation>build_face.png</translation>
        </message>
        <message>
            <source>ICON_DLG_BUILD_FACE_SURFACE</source>
            <translation>build_face_surface.png</translation>
        </message>
        <message>
            <source>ICON_DLG_BUILD_FACE_CONSTRAINTS</source>
            <translation>build_face_constraints.png</translation>
        </message>
	<message>
            <source>ICON_DLG_FACE_HW</source>
            <translation>face_hw.png</translation>
        </message>
	<message>
            <source>ICON_DLG_FACE_OBJ_HW</source>
            <translation>face_vechw.png</translation>
        </message>
        <message>
            <source>ICON_DLG_BUILD_SHELL</source>
            <translation>build_shell.png</translation>
        </message>
        <message>
            <source>ICON_DLG_SOLID_FROM_FACES</source>
            <translation>solid_from_faces.png</translation>
        </message>
        <message>
            <source>ICON_DLG_BUILD_SOLID</source>
            <translation>build_solid.png</translation>
        </message>
        <message>
            <source>ICON_DLG_BUILD_WIRE</source>
            <translation>build_wire.png</translation>
        </message>
        <message>
            <source>ICON_DLG_CENTERMASS</source>
            <translation>centergravity.png</translation>
        </message>
        <message>
            <source>ICON_DLG_CHAMFER</source>
            <translation>chamfer.png</translation>
        </message>
        <message>
            <source>ICON_DLG_CHAMFER_ALL</source>
            <translation>chamferall.png</translation>
        </message>
        <message>
            <source>ICON_DLG_CHAMFER_EDGE</source>
            <translation>chamferedge.png</translation>
        </message>
        <message>
            <source>ICON_DLG_CHAMFER_EDGE_FROM_FACE</source>
            <translation>chamferedgefromface.png</translation>
        </message>
        <message>
            <source>ICON_DLG_CHAMFER_FACE</source>
            <translation>chamferface.png</translation>
        </message>
        <message>
            <source>ICON_DLG_CHANGE_ORIENTATION</source>
            <translation>change_orientation.png</translation>
        </message>
        <message>
            <source>ICON_DLG_CHANGE_DIRECTION</source>
            <translation>change_direction.png</translation>
        </message>
        <message>
            <source>ICON_DLG_REMOVE_WEBS</source>
            <translation>remove_webs.png</translation>
        </message>
        <message>
            <source>ICON_DLG_REMOVE_EXTRA_EDGES</source>
            <translation>remove_extra_edges.png</translation>
        </message>
        <message>
            <source>ICON_DLG_FUSE_EDGES</source>
            <translation>fuse_collinear_edges.png</translation>
        </message>
        <message>
            <source>ICON_DLG_UNION_FACES</source>
            <translation>union_faces.png</translation>
        </message>
        <message>
            <source>ICON_DLG_INSPECT_OBJECT</source>
            <translation>inspect_object.png</translation>
        </message>
        <message>
            <source>ICON_DLG_CHECKSHAPE</source>
            <translation>check.png</translation>
        </message>
        <message>
            <source>ICON_DLG_CHECK_COMPOUND_OF_BLOCKS</source>
            <translation>check_blocks_compound.png</translation>
        </message>
        <message>
            <source>ICON_DLG_GETNONBLOCKS</source>
            <translation>get_non_blocks.png</translation>
        </message>
        <message>
            <source>ICON_DLG_CHECK_SELF_INTERSECTIONS</source>
            <translation>check_self_intersections.png</translation>
        </message>
        <message>
            <source>ICON_DLG_FAST_CHECK_INTERSECTIONS</source>
            <translation>fast_intersect.png</translation>
        </message>
        <message>
            <source>ICON_DLG_CIRCLE_PNTS</source>
            <translation>circle3points.png</translation>
        </message>
        <message>
            <source>ICON_DLG_CIRCLE_PV</source>
            <translation>circlepointvector.png</translation>
        </message>
        <message>
            <source>ICON_DLG_CIRCLE_C2P</source>
            <translation>circlecenter2pnts.png</translation>
        </message>
        <message>
            <source>ICON_DLG_CLOSECONTOUR</source>
            <translation>closecontour.png</translation>
        </message>
        <message>
            <source>ICON_DLG_COMMON</source>
            <translation>common.png</translation>
        </message>
        <message>
            <source>ICON_DLG_CONE_DXYZ</source>
            <translation>conedxyz.png</translation>
        </message>
        <message>
            <source>ICON_DLG_CONE_PV</source>
            <translation>conepointvector.png</translation>
        </message>
        <message>
            <source>ICON_DLG_CUT</source>
            <translation>cut.png</translation>
        </message>
        <message>
            <source>ICON_DLG_CYLINDER_DXYZ</source>
            <translation>cylinderdxyz.png</translation>
        </message>
        <message>
            <source>ICON_DLG_CYLINDER_PV</source>
            <translation>cylinderpointvector.png</translation>
        </message>
        <message>
            <source>ICON_DLG_DIVIDE_EDGE</source>
            <translation>pointonedge.png</translation>
        </message>
        <message>
            <source>ICON_DLG_DIVIDE_EDGE_BY_PNT</source>
            <translation>pointonedgebypoint.png</translation>
        </message>
        <message>
            <source>ICON_DLG_ELLIPSE_PV</source>
            <translation>ellipsepointvector.png</translation>
        </message>
        <message>
            <source>ICON_DLG_FILLET</source>
            <translation>fillet.png</translation>
        </message>
	<message>
            <source>ICON_DLG_FILLET_1D</source>
            <translation>fillet1d.png</translation>
        </message>
	<message>
            <source>ICON_DLG_FILLET_2D</source>
            <translation>fillet2d.png</translation>
        </message>
        <message>
            <source>ICON_DLG_FILLET_ALL</source>
            <translation>filletall.png</translation>
        </message>
        <message>
            <source>ICON_DLG_FILLET_EDGE</source>
            <translation>filletedge.png</translation>
        </message>
        <message>
            <source>ICON_DLG_FILLET_WIRE</source>
            <translation>filletwire.png</translation>
        </message>
        <message>
            <source>ICON_DLG_FILLET_FACE</source>
            <translation>filletface.png</translation>
        </message>
        <message>
            <source>ICON_DLG_FILLING</source>
            <translation>filling.png</translation>
        </message>
        <message>
            <source>ICON_DLG_FREE_FACES</source>
            <translation>free_faces.png</translation>
        </message>
        <message>
            <source>ICON_DLG_FREE_BOUNDS</source>
            <translation>free_bound.png</translation>
        </message>
        <message>
            <source>ICON_DLG_FUSE</source>
            <translation>fuse.png</translation>
        </message>
        <message>
            <source>ICON_DLG_GLUE_FACES</source>
            <translation>glue.png</translation>
        </message>
        <message>
            <source>ICON_DLG_GLUE_FACES2</source>
            <translation>glue2.png</translation>
        </message>
        <message>
            <source>ICON_DLG_GLUE_EDGES</source>
            <translation>glue.png</translation>
        </message>
        <message>
            <source>ICON_DLG_GLUE_EDGES2</source>
            <translation>glue2.png</translation>
        </message>
        <message>
            <source>ICON_DLG_LIMIT_TOLERANCE</source>
            <translation>limit_tolerance.png</translation>
        </message>
        <message>
            <source>ICON_DLG_INERTIA</source>
            <translation>axisinertia.png</translation>
        </message>
        <message>
            <source>ICON_DLG_INTERPOL</source>
            <translation>interpol.png</translation>
        </message>
        <message>
            <source>ICON_DLG_IMPORT_PICTURE</source>
            <translation>import_picture.png</translation>
        </message>
        <message>
            <source>ICON_DLG_LINE_2P</source>
            <translation>line2points.png</translation>
        </message>
        <message>
            <source>ICON_DLG_LINE_2F</source>
            <translation>line2faces.png</translation>
        </message>
        <message>
            <source>ICON_DLG_MINDIST</source>
            <translation>mindist.png</translation>
        </message>
        <message>
            <source>ICON_DLG_MIRROR_AXE</source>
            <translation>mirrorAxe.png</translation>
        </message>
        <message>
            <source>ICON_DLG_MIRROR_PLANE</source>
            <translation>mirrorPlane.png</translation>
        </message>
        <message>
            <source>ICON_DLG_MIRROR_POINT</source>
            <translation>mirrorPoint.png</translation>
        </message>
        <message>
            <source>ICON_DLG_MULTIROTATION</source>
            <translation>multirotation.png</translation>
        </message>
        <message>
            <source>ICON_DLG_MULTIROTATION_DOUBLE</source>
            <translation>multirotationdouble.png</translation>
        </message>
        <message>
            <source>ICON_DLG_MULTIROTATION_SIMPLE</source>
            <translation>multirotationsimple.png</translation>
        </message>
        <message>
            <source>ICON_DLG_MULTITRANSLATION</source>
            <translation>multitranslation.png</translation>
        </message>
        <message>
            <source>ICON_DLG_MULTITRANSLATION_DOUBLE</source>
            <translation>multitranslationdouble.png</translation>
        </message>
        <message>
            <source>ICON_DLG_MULTITRANSLATION_SIMPLE</source>
            <translation>multitranslationsimple.png</translation>
        </message>
        <message>
            <source>ICON_DLG_OFFSET</source>
            <translation>offset.png</translation>
        </message>
        <message>
            <source>ICON_DLG_PROJECTION_ON_FACE</source>
            <translation>projection.png</translation>
        </message>
        <message>
            <source>ICON_DLG_PROJECTION_ON_WIRE</source>
            <translation>projection_on_wire.png</translation>
        </message>
        <message>
            <source>ICON_DLG_PROJECTION_ON_EDGE</source>
            <translation>projection_on_edge.png</translation>
        </message>
        <message>
            <source>ICON_DLG_EXTEND_EDGE</source>
            <translation>edgeextension.png</translation>
        </message>
        <message>
            <source>ICON_DLG_EXTEND_FACE</source>
            <translation>faceextension.png</translation>
        </message>
        <message>
            <source>ICO_DLG_PROJ_ON_CYL</source>
            <translation>proj_on_cyl.png</translation>
        </message>
        <message>
            <source>ICON_DLG_PARTITION</source>
            <translation>partition.png</translation>
        </message>
        <message>
            <source>ICON_DLG_PARTITION_KEEP_FACES</source>
            <translation>partitionkeep.png</translation>
        </message>
        <message>
            <source>ICON_DLG_PARTITION_PLANE</source>
            <translation>partitionplane.png</translation>
        </message>
        <message>
            <source>ICON_DLG_PIPE_PATH</source>
            <translation>pipe.png</translation>
        </message>
        <message>
            <source>ICON_DLG_PIPE</source>
            <translation>pipe.png</translation>
        </message>
        <message>
            <source>ICON_DLG_PIPE_BINORMAL</source>
            <translation>pipebinormal.png</translation>
        </message>
        <message>
            <source>ICON_DLG_PIPE_SECTION</source>
            <translation>pipesections.png</translation>
        </message>
        <message>
            <source>ICON_DLG_PLANE_3PNTS</source>
            <translation>plane3points.png</translation>
        </message>
        <message>
            <source>ICON_DLG_PLANE_FACE</source>
            <translation>planeface.png</translation>
        </message>
        <message>
            <source>ICON_DLG_PLANE_PV</source>
            <translation>planepointvector.png</translation>
        </message>
        <message>
            <source>ICON_DLG_POINT</source>
            <translation>point2.png</translation>
        </message>
        <message>
            <source>ICON_DLG_POINT_EDGE</source>
            <translation>pointonedge.png</translation>
        </message>
        <message>
            <source>ICON_DLG_POINT_REF</source>
            <translation>point3.png</translation>
        </message>
        <message>
            <source>ICON_DLG_POINT_LINES</source>
            <translation>point_line_intersection.png</translation>
        </message>
        <message>
            <source>ICON_DLG_POLYLINE</source>
            <translation>polyline.png</translation>
        </message>
        <message>
            <source>ICON_DLG_POSITION</source>
            <translation>position.png</translation>
        </message>
        <message>
            <source>ICON_DLG_NORMALE</source>
            <translation>normale.png</translation>
        </message>
        <message>
            <source>ICON_DLG_ANGLE</source>
            <translation>angle.png</translation>
        </message>
        <message>
            <source>ICON_DLG_POSITION2</source>
            <translation>position2.png</translation>
        </message>
	<message>
            <source>ICON_DLG_POSITION3</source>
            <translation>position3.png</translation>
        </message>
        <message>
            <source>ICON_DLG_PRISM</source>
            <translation>prism.png</translation>
        </message>
        <message>
            <source>ICON_DLG_PRISM_2P</source>
            <translation>prism2.png</translation>
        </message>
	<message>
            <source>ICON_DLG_PRISM_DXDYDZ</source>
            <translation>prism3.png</translation>
        </message>
        <message>
            <source>ICON_DLG_THICKNESS</source>
            <translation>thickness.png</translation>
        </message>
        <message>
            <source>ICON_DLG_THICKNESS_HOLLOWED</source>
            <translation>thickness2.png</translation>
        </message>
        <message>
            <source>ICON_DLG_PROPAGATE</source>
            <translation>propagate.png</translation>
        </message>
        <message>
            <source>ICON_DLG_QUAD_FACE_2_EDGE</source>
            <translation>block_face_2e.png</translation>
        </message>
        <message>
            <source>ICON_DLG_QUAD_FACE_4_EDGE</source>
            <translation>block_face_4e.png</translation>
        </message>
        <message>
            <source>ICON_DLG_QUAD_FACE_4_VERT</source>
            <translation>block_face_4v.png</translation>
        </message>
        <message>
            <source>ICON_DLG_RECTANGLE</source>
            <translation>rectangle.png</translation>
        </message>
        <message>
            <source>ICON_DLG_REDO</source>
            <translation>redo.png</translation>
        </message>
        <message>
            <source>ICON_DLG_REVOL</source>
            <translation>revol.png</translation>
        </message>
        <message>
            <source>ICON_DLG_ROTATION</source>
            <translation>rotate.png</translation>
        </message>
        <message>
            <source>ICON_DLG_ROTATION_THREE_POINTS</source>
            <translation>rotatepnt.png</translation>
        </message>
        <message>
            <source>ICON_DLG_SCALE</source>
            <translation>scale.png</translation>
        </message>
        <message>
            <source>ICON_DLG_SECTION</source>
            <translation>section.png</translation>
        </message>
        <message>
            <source>ICON_DLG_SEWING</source>
            <translation>sewing.png</translation>
        </message>
        <message>
            <source>ICON_DLG_SHAPEPROCESS</source>
            <translation>shapeprocess.png</translation>
        </message>
        <message>
            <source>ICON_DLG_SPHERE_DXYZ</source>
            <translation>spheredxyz.png</translation>
        </message>
        <message>
            <source>ICON_DLG_SPHERE_P</source>
            <translation>spherepoint.png</translation>
        </message>
        <message>
            <source>ICON_DLG_SPLINE</source>
            <translation>spline.png</translation>
        </message>
        <message>
            <source>ICON_DLG_SUBSHAPE</source>
            <translation>subshape.png</translation>
        </message>
        <message>
            <source>ICON_DLG_SUPPRESS_HOLES</source>
            <translation>supressHolesOnFaceShell.png</translation>
        </message>
        <message>
            <source>ICON_DLG_SUPPRESS_INT_WIRES</source>
            <translation>suppressintwires.png</translation>
        </message>
        <message>
            <source>ICON_DLG_SUPRESS_FACE</source>
            <translation>supressface.png</translation>
        </message>
        <message>
            <source>ICON_DLG_SUPRESS_HOLE</source>
            <translation>supresshole.png</translation>
        </message>
        <message>
            <source>ICON_DLG_SUPRESS_HOLE_FACE_SHELL</source>
            <translation>supressHolesOnFaceShell.png</translation>
        </message>
        <message>
            <source>ICON_DLG_TOLERANCE</source>
            <translation>tolerance.png</translation>
        </message>
        <message>
            <source>ICON_DLG_TORUS_DXYZ</source>
            <translation>torusdxyz.png</translation>
        </message>
        <message>
            <source>ICON_DLG_TORUS_PV</source>
            <translation>toruspointvector.png</translation>
        </message>
        <message>
            <source>ICON_DLG_TRANSLATION_DXYZ</source>
            <translation>translationDxyz.png</translation>
        </message>
        <message>
            <source>ICON_DLG_TRANSLATION_POINTS</source>
            <translation>translationPoints.png</translation>
        </message>
        <message>
            <source>ICON_DLG_TRANSLATION_VECTOR</source>
            <translation>translationVector.png</translation>
        </message>
        <message>
            <source>ICON_DLG_UNDO</source>
            <translation>undo.png</translation>
        </message>
        <message>
            <source>ICON_DLG_VECTOR_2P</source>
            <translation>vector2points.png</translation>
        </message>
        <message>
            <source>ICON_DLG_VECTOR_DXYZ</source>
            <translation>vectordxyz.png</translation>
        </message>
        <message>
            <source>ICON_DLG_WHATIS</source>
            <translation>whatis.png</translation>
        </message>
        <message>
            <source>ICON_DLG_WPLANE_FACE</source>
            <translation>planeworkingface.png</translation>
        </message>
        <message>
            <source>ICON_DLG_WPLANE_ORIGIN</source>
            <translation>planeworkingorigin.png</translation>
        </message>
        <message>
            <source>ICON_DLG_WPLANE_VECTOR</source>
            <translation>planeworkingvector.png</translation>
        </message>
        <message>
            <source>ICON_MARKER</source>
            <translation>marker.png</translation>
        </message>
        <message>
            <source>ICON_MARKER2</source>
            <translation>marker2.png</translation>
        </message>
        <message>
            <source>ICON_MARKER3</source>
            <translation>marker3.png</translation>
        </message>
        <message>
            <source>ICON_OBJBROWSER_BLOCK</source>
            <translation>tree_block.png</translation>
        </message>
        <message>
            <source>ICON_OBJBROWSER_COMPOUND</source>
            <translation>tree_compound.png</translation>
        </message>
        <message>
            <source>ICON_OBJBROWSER_COMPSOLID</source>
            <translation>tree_compsolid.png</translation>
        </message>
        <message>
            <source>ICON_OBJBROWSER_EDGE</source>
            <translation>tree_edge.png</translation>
        </message>
        <message>
            <source>ICON_OBJBROWSER_FACE</source>
            <translation>tree_face.png</translation>
        </message>
        <message>
            <source>ICON_OBJBROWSER_GROUP_EDGE</source>
            <translation>tree_group_edge.png</translation>
        </message>
        <message>
            <source>ICON_OBJBROWSER_GROUP_FACE</source>
            <translation>tree_group_face.png</translation>
        </message>
        <message>
            <source>ICON_OBJBROWSER_GROUP_PNT</source>
            <translation>tree_group_vertex.png</translation>
        </message>
        <message>
            <source>ICON_OBJBROWSER_GROUP_SOLID</source>
            <translation>tree_group_solid.png</translation>
        </message>
        <message>
            <source>ICON_OBJBROWSER_FIELD_EDGE</source>
            <translation>tree_field_edge.png</translation>
        </message>
        <message>
            <source>ICON_OBJBROWSER_FIELD_FACE</source>
            <translation>tree_field_face.png</translation>
        </message>
        <message>
            <source>ICON_OBJBROWSER_FIELD_PNT</source>
            <translation>tree_field_vertex.png</translation>
        </message>
        <message>
            <source>ICON_OBJBROWSER_FIELD_SOLID</source>
            <translation>tree_field_solid.png</translation>
        </message>
        <message>
            <source>ICON_OBJBROWSER_Geometry</source>
            <translation>geometry.png</translation>
        </message>
        <message>
            <source>ICON_OBJBROWSER_LCS</source>
            <translation>tree_lcs.png</translation>
        </message>
        <message>
            <source>ICON_OBJBROWSER_SHAPE</source>
            <translation>tree_shape.png</translation>
        </message>
        <message>
            <source>ICON_OBJBROWSER_SHELL</source>
            <translation>tree_shell.png</translation>
        </message>
        <message>
            <source>ICON_OBJBROWSER_SOLID</source>
            <translation>tree_solid.png</translation>
        </message>
        <message>
            <source>ICON_OBJBROWSER_VERTEX</source>
            <translation>tree_vertex.png</translation>
        </message>
        <message>
            <source>ICON_OBJBROWSER_WIRE</source>
            <translation>tree_wire.png</translation>
        </message>
        <message>
            <source>ICON_SELECT</source>
            <translation>select1.png</translation>
        </message>
	<message>
            <source>ICON_VERTEX_MARKER_1</source>
            <translation>marker_1.png</translation>
        </message>
	<message>
            <source>ICON_VERTEX_MARKER_2</source>
            <translation>marker_2.png</translation>
        </message>
	<message>
            <source>ICON_VERTEX_MARKER_3</source>
            <translation>marker_3.png</translation>
        </message>
	<message>
            <source>ICON_VERTEX_MARKER_4</source>
            <translation>marker_4.png</translation>
        </message>
	<message>
            <source>ICON_VERTEX_MARKER_5</source>
            <translation>marker_5.png</translation>
        </message>
	<message>
            <source>ICON_VERTEX_MARKER_6</source>
            <translation>marker_6.png</translation>
        </message>
	<message>
            <source>ICON_VERTEX_MARKER_7</source>
            <translation>marker_7.png</translation>
        </message>
	<message>
            <source>ICON_VERTEX_MARKER_8</source>
            <translation>marker_8.png</translation>
        </message>
	<message>
            <source>ICON_VERTEX_MARKER_9</source>
            <translation>marker_9.png</translation>
        </message>
	<message>
            <source>ICON_VERTEX_MARKER_10</source>
            <translation>marker_10.png</translation>
        </message>
	<message>
            <source>ICON_VERTEX_MARKER_11</source>
            <translation>marker_11.png</translation>
        </message>
	<message>
            <source>ICON_VERTEX_MARKER_12</source>
            <translation>marker_12.png</translation>
        </message>
	<message>
            <source>ICON_VERTEX_MARKER_13</source>
            <translation>marker_13.png</translation>
        </message>
        <message>
            <source>ICON_SURFACE_FROM_FACE</source>
            <translation>facetosurface.png</translation>
        </message>
        <message>
            <source>ICO_ARC</source>
            <translation>arc.png</translation>
        </message>
        <message>
            <source>ICO_ARCHIMEDE</source>
            <translation>archimede.png</translation>
        </message>
        <message>
            <source>ICO_BASIC_PROPS</source>
            <translation>basicproperties.png</translation>
        </message>
        <message>
            <source>ICO_BND_BOX</source>
            <translation>bounding.png</translation>
        </message>
        <message>
            <source>ICO_BOX</source>
            <translation>box.png</translation>
        </message>
        <message>
            <source>ICO_CHAMFER</source>
            <translation>chamfer.png</translation>
        </message>
        <message>
            <source>ICO_CHANGE_ORIENTATION</source>
            <translation>change_orientation.png</translation>
        </message>
        <message>
            <source>ICO_CHECK</source>
            <translation>check.png</translation>
        </message>
        <message>
            <source>ICO_CHECK_COMPOUND</source>
            <translation>check_blocks_compound.png</translation>
        </message>
        <message>
            <source>ICO_GET_NON_BLOCKS</source>
            <translation>get_non_blocks.png</translation>
        </message>
        <message>
            <source>ICO_CHECK_SELF_INTERSECTIONS</source>
            <translation>check_self_intersections.png</translation>
        </message>
        <message>
            <source>ICO_FAST_CHECK_INTERSECTIONS</source>
            <translation>fast_intersect.png</translation>
        </message>
        <message>
            <source>ICO_CHECK_FREE_BNDS</source>
            <translation>free_bound.png</translation>
        </message>
        <message>
            <source>ICO_CHECK_FREE_FACES</source>
            <translation>free_faces.png</translation>
        </message>
        <message>
            <source>ICO_CIRCLE</source>
            <translation>circle.png</translation>
        </message>
        <message>
            <source>ICO_CLOSE_CONTOUR</source>
            <translation>closecontour.png</translation>
        </message>
        <message>
            <source>ICO_COMMON</source>
            <translation>common.png</translation>
        </message>
        <message>
            <source>ICO_GROUP_INTERSECT</source>
            <translation>common.png</translation>
        </message>
        <message>
            <source>ICO_COMPOUND</source>
            <translation>build_compound.png</translation>
        </message>
        <message>
            <source>ICO_COMPOUND_SEL_ONLY</source>
            <translation>build_compound.png</translation>
        </message>
        <message>
            <source>ICO_CONE</source>
            <translation>cone.png</translation>
        </message>
        <message>
            <source>ICO_CURVE</source>
            <translation>spline.png</translation>
        </message>
        <message>
            <source>ICO_CUT</source>
            <translation>cut.png</translation>
        </message>
        <message>
            <source>ICO_GROUP_CUT</source>
            <translation>cut.png</translation>
        </message>
        <message>
            <source>ICO_CYLINDER</source>
            <translation>cylinder.png</translation>
        </message>
        <message>
            <source>ICO_DELETE</source>
            <translation>delete.png</translation>
        </message>
        <message>
            <source>ICO_DISK</source>
            <translation>disk.png</translation>
        </message>
        <message>
            <source>ICO_DISPLAY</source>
            <translation>display.png</translation>
        </message>
        <message>
            <source>ICO_DISPLAY_ALL</source>
            <translation>displayall.png</translation>
        </message>
        <message>
            <source>ICO_DISPLAY_ONLY</source>
            <translation>displayonly.png</translation>
        </message>
        <message>
            <source>ICO_DRAFT</source>
            <translation>draft.png</translation>
        </message>
        <message>
            <source>ICO_EDGE</source>
            <translation>build_edge.png</translation>
        </message>
        <message>
            <source>ICO_EDGE_SEL_ONLY</source>
            <translation>build_edge.png</translation>
        </message>
        <message>
            <source>ICO_ELLIPSE</source>
            <translation>ellipse.png</translation>
        </message>
        <message>
            <source>ICO_ERASE</source>
            <translation>erase.png</translation>
        </message>
        <message>
            <source>ICO_ERASE_ALL</source>
            <translation>eraseall.png</translation>
        </message>
        <message>
            <source>ICO_EXPLODE</source>
            <translation>subshape.png</translation>
        </message>
        <message>
            <source>ICO_EXPLODE_BLOCKS</source>
            <translation>subshape.png</translation>
        </message>
         <message>
            <source>ICO_EXTRUDED_BOSS</source>
            <translation>extruded_boss.png</translation>
        </message>
        <message>
            <source>ICO_EXTRUDED_CUT</source>
            <translation>extruded_cut.png</translation>
        </message>
        <message>
            <source>ICO_EXTRUSION</source>
            <translation>prism.png</translation>
        </message>
        <message>
            <source>ICO_THICKNESS</source>
            <translation>thickness.png</translation>
        </message>
        <message>
            <source>ICO_FACE</source>
            <translation>build_face.png</translation>
        </message>
        <message>
            <source>ICO_RECTANGLE</source>
            <translation>build_face.png</translation>
        </message>
        <message>
            <source>ICO_FACE_SEL_ONLY</source>
            <translation>build_face.png</translation>
        </message>
        <message>
            <source>ICO_FEATURE_DETECTION</source>
            <translation>feature_detect.png</translation>
        </message>
        <message>
            <source>ICO_FILLET</source>
            <translation>fillet.png</translation>
        </message>
	<message>
            <source>ICO_FILLET_1D</source>
            <translation>fillet1d.png</translation>
        </message>
	<message>
            <source>ICO_FILLET_2D</source>
            <translation>fillet2d.png</translation>
        </message>
        <message>
            <source>ICO_FILLING</source>
            <translation>filling.png</translation>
        </message>
        <message>
            <source>ICO_FUSE</source>
            <translation>fuse.png</translation>
        </message>
        <message>
            <source>ICO_GROUP_UNION</source>
            <translation>fuse.png</translation>
        </message>
        <message>
            <source>ICO_GLUE_FACES</source>
            <translation>glue.png</translation>
        </message>
        <message>
            <source>ICO_GLUE_EDGES</source>
            <translation>glue.png</translation>
        </message>
        <message>
            <source>ICO_LIMIT_TOLERANCE</source>
            <translation>limit_tolerance.png</translation>
        </message>
        <message>
            <source>ICO_GROUP_CREATE</source>
            <translation>group_new.png</translation>
        </message>
        <message>
            <source>ICO_GROUP_EDIT</source>
            <translation>group_edit.png</translation>
        </message>
        <message>
            <source>ICO_FIELD_CREATE</source>
            <translation>field_new.png</translation>
        </message>
        <message>
            <source>ICO_FIELD_EDIT</source>
            <translation>field_edit.png</translation>
        </message>
        <message>
            <source>ICO_ADD_FIELD_STEP</source>
            <translation>field_new.png</translation>
        </message>
        <message>
            <source>ICO_HEX_SOLID</source>
            <translation>box.png</translation>
        </message>
        <message>
            <source>ICO_INERTIA</source>
            <translation>axisinertia.png</translation>
        </message>
        <message>
            <source>ICO_PICTURE_IMPORT</source>
            <translation>import_picture.png</translation>
        </message>
	    <message>
            <source>ICO_LINE</source>
            <translation>line.png</translation>
        </message>
        <message>
            <source>ICO_LOCAL_CS</source>
            <translation>marker.png</translation>
        </message>
        <message>
            <source>ICO_MASS_CENTER</source>
            <translation>centergravity.png</translation>
        </message>
        <message>
            <source>ICO_MIN_DIST</source>
            <translation>mindist.png</translation>
        </message>
        <message>
            <source>ICO_MIRROR</source>
            <translation>mirrorPlane.png</translation>
        </message>
        <message>
            <source>ICO_MODIFY_LOCATION</source>
            <translation>position2.png</translation>
        </message>
        <message>
            <source>ICO_MUL_ROTATION</source>
            <translation>multirotation.png</translation>
        </message>
        <message>
            <source>ICO_MUL_TRANSFORM</source>
            <translation>multirotation.png</translation>
        </message>
        <message>
            <source>ICO_MUL_TRANSLATION</source>
            <translation>multitranslation.png</translation>
        </message>
        <message>
            <source>ICO_OFFSET</source>
            <translation>offset.png</translation>
        </message>
        <message>
            <source>ICO_PROJECTION</source>
            <translation>projection.png</translation>
        </message>
        <message>
            <source>ICO_EXTENSION</source>
            <translation>edgeextension.png</translation>
        </message>
        <message>
            <source>ICO_PROJ_ON_CYL</source>
            <translation>proj_on_cyl.png</translation>
        </message>
        <message>
            <source>ICO_ORIGIN_AND_VECTORS</source>
            <translation>origin_and_vectors.png</translation>
        </message>
        <message>
            <source>ICO_PARTITION</source>
            <translation>partition.png</translation>
        </message>
        <message>
            <source>ICO_PIPE</source>
            <translation>pipe.png</translation>
        </message>
        <message>
            <source>ICO_PIPE_PATH</source>
            <translation>pipe.png</translation>
        </message>
        <message>
            <source>ICO_PLANE</source>
            <translation>plane.png</translation>
        </message>
        <message>
            <source>ICO_REMOVE_WEBS</source>
            <translation>remove_webs.png</translation>
        </message>
        <message>
            <source>ICO_REMOVE_EXTRA_EDGES</source>
            <translation>remove_extra_edges.png</translation>
        </message>
        <message>
            <source>ICO_FUSE_EDGES</source>
            <translation>fuse_collinear_edges.png</translation>
        </message>
        <message>
            <source>ICO_UNION_FACES</source>
            <translation>union_faces.png</translation>
        </message>
        <message>
            <source>ICO_NORMALE</source>
            <translation>normale.png</translation>
        </message>
        <message>
            <source>ICO_MEASURE_ANGLE</source>
            <translation>angle.png</translation>
        </message>
        <message>
            <source>ICO_MANAGE_DIMENSIONS</source>
            <translation>managedimensions.png</translation>
        </message>
        <message>
            <source>ICO_POINT</source>
            <translation>point2.png</translation>
        </message>
        <message>
            <source>ICO_POINT_COORDS</source>
            <translation>point_coord.png</translation>
        </message>
        <message>
            <source>ICO_POINT_ON_EDGE</source>
            <translation>pointonedge.png</translation>
        </message>
        <message>
            <source>ICO_POP_CREATE_GROUP</source>
            <translation>group_new.png</translation>
        </message>
        <message>
            <source>ICO_POP_EDIT_FIELD</source>
            <translation>field_edit.png</translation>
        </message>
        <message>
            <source>ICO_PROPAGATE</source>
            <translation>propagate.png</translation>
        </message>
        <message>
            <source>ICO_Q_FACE</source>
            <translation>build_face.png</translation>
        </message>
        <message>
            <source>ICO_REVOLUTION</source>
            <translation>revol.png</translation>
        </message>
        <message>
            <source>ICO_ROTATION</source>
            <translation>rotate.png</translation>
        </message>
        <message>
            <source>ICO_SCALE</source>
            <translation>scale.png</translation>
        </message>
        <message>
            <source>ICO_SECTION</source>
            <translation>section.png</translation>
        </message>
        <message>
            <source>ICO_SEWING</source>
            <translation>sewing.png</translation>
        </message>
	<message>
            <source>ICO_WIREFRAME</source>
            <translation>wireframe.png</translation>
        </message>
	<message>
            <source>ICO_SHADING</source>
            <translation>shading.png</translation>
        </message>
	<message>
            <source>ICO_SHADING_WITH_EDGES</source>
            <translation>shading_with_edges.png</translation>
        </message>
	<message>
            <source>ICO_VECTOR_MODE</source>
            <translation>vector_mode.png</translation>
        </message>
        <message>
            <source>ICO_SHAPE_PROCESS</source>
            <translation>shapeprocess.png</translation>
        </message>
        <message>
            <source>ICO_SHELL</source>
            <translation>build_shell.png</translation>
        </message>
        <message>
            <source>ICO_SHELL_SEL_ONLY</source>
            <translation>build_shell.png</translation>
        </message>
        <message>
          <source>ICO_CURVE_CREATOR</source>
          <translation>polyline.png</translation>
        </message>
        <message>
            <source>ICO_SKETCH</source>
            <translation>sketch.png</translation>
        </message>
	<message>
            <source>ICO_3DSKETCH</source>
            <translation>3dsketch.png</translation>
        </message>
        <message>
            <source>ICO_ISOLINE</source>
            <translation>isoline.png</translation>
        </message>
        <message>
            <source>ICO_ISOLINE_V</source>
            <translation>isoline_v.png</translation>
        </message>
        <message>
            <source>ICO_SURFACE_FROM_FACE</source>
            <translation>facetosurface.png</translation>
        </message>
        <message>
            <source>ICO_SOLID</source>
            <translation>build_solid.png</translation>
        </message>
        <message>
            <source>ICO_SOLID_FROM_FACES</source>
            <translation>solid_from_face.png</translation>
        </message>
        <message>
            <source>ICO_SOLID_SEL_ONLY</source>
            <translation>build_solid.png</translation>
        </message>
        <message>
            <source>ICO_SPHERE</source>
            <translation>sphere.png</translation>
        </message>
        <message>
            <source>ICO_SUPPERSS_HOLES</source>
            <translation>supresshole.png</translation>
        </message>
        <message>
            <source>ICO_SUPPRESS_FACES</source>
            <translation>supressface.png</translation>
        </message>
        <message>
            <source>ICO_SUPPRESS_INT_WIRES</source>
            <translation>suppressintwires.png</translation>
        </message>
        <message>
            <source>ICO_TOLERANCE</source>
            <translation>tolerance.png</translation>
        </message>
        <message>
            <source>ICO_TORUS</source>
            <translation>torus.png</translation>
        </message>
        <message>
            <source>ICO_TRANSLATION</source>
            <translation>translationVector.png</translation>
        </message>
        <message>
            <source>ICO_VECTOR</source>
            <translation>vector.png</translation>
        </message>
        <message>
            <source>ICO_VERTEX_SEL_ONLY</source>
            <translation>point2.png</translation>
        </message>
        <message>
            <source>ICO_WHAT_IS</source>
            <translation>whatis.png</translation>
        </message>
        <message>
            <source>ICO_WIRE</source>
            <translation>build_wire.png</translation>
        </message>
        <message>
            <source>ICO_WIRE_SEL_ONLY</source>
            <translation>build_wire.png</translation>
        </message>
        <message>
            <source>ICO_WORK_PLANE</source>
            <translation>planeWorking.png</translation>
        </message>
        <message>
            <source>ICO_GET_SHAPES_ON_SHAPE</source>
            <translation>shapesonshape.png</translation>
        </message>
        <message>
            <source>ICO_GET_SHARED_SHAPES</source>
            <translation>shared_shapes.png</translation>
        </message>
        <message>
            <source>ICO_TRANSFER_DATA</source>
            <translation>transfer_data.png</translation>
        </message>
        <message>
            <source>ICO_EXTRACTION</source>
            <translation>extract.png</translation>
        </message>
        <message>
            <source>ICO_IMPORT_SHAPE</source>
            <translation>import.png</translation>
        </message>
        <message>
            <source>ICON_DLG_POINT_FACE</source>
            <translation>pointonface.png</translation>
        </message>
        <message>
            <source>ICON_DLG_SHAPES_ON_SHAPE</source>
            <translation>shapesonshape.png</translation>
        </message>
        <message>
            <source>ICON_DLG_SHARED_SHAPES</source>
            <translation>shared_shapes.png</translation>
        </message>
        <message>
            <source>ICON_DLG_TRANSFER_DATA</source>
            <translation>transfer_data.png</translation>
        </message>
        <message>
            <source>ICON_DLG_EXTRACTION</source>
            <translation>extract.png</translation>
        </message>
        <message>
            <source>ICON_DLG_SCALE_ALONG_AXES</source>
            <translation>scale_along_axes.png</translation>
        </message>
	<!-- @@ insert new functions before this line @@ do not remove this line @@ -->
    </context>
</TS>
