<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="ja" sourcelanguage="en">
  <context>
    <name>@default</name>
    <message>
      <source>MEN_EXPORTXAO</source>
      <translation>XAOエクスポート</translation>
    </message>
    <message>
      <source>TOP_EXPORTXAO</source>
      <translation>XAOのエクスポート</translation>
    </message>
    <message>
      <source>STB_EXPORTXAO</source>
      <translation>XAOのエクスポート</translation>
    </message>
    <message>
      <source>MEN_IMPORTXAO</source>
      <translation>XAOインポート</translation>
    </message>
    <message>
      <source>TOP_IMPORTXAO</source>
      <translation>XAOのインポート</translation>
    </message>
    <message>
      <source>STB_IMPORTXAO</source>
      <translation>XAOのインポート</translation>
    </message>
    <message>
      <source>XAOPLUGIN_IMPORT_SELECT</source>
      <translation>XAOからインポート</translation>
    </message>
    <message>
      <source>XAOPLUGIN_EXPORT_SELECT</source>
      <translation>XAOへのエクスポート</translation>
    </message>
    <message>
      <source>XAOPLUGIN_FILES</source>
      <translation>XAO ファイル (*.xao)</translation>
    </message>
  </context>
  <context>
    <name>XAOPlugin_ExportDlg</name>
    <message>
      <source>XAOPLUGIN_EXPORT_TITLE</source>
      <translation>XAOエクスポート</translation>
    </message>
    <message>
      <source>XAOPLUGIN_EXPORTXAO</source>
      <translation>XAOエクスポート</translation>
    </message>
    <message>
      <source>XAOPLUGIN_EXPORT_INGSHAPE</source>
      <translation>オブジェクト</translation>
    </message>
    <message>
      <source>XAOPLUGIN_EXPORT_FILENAME</source>
      <translation>ファイル</translation>
    </message>
    <message>
      <source>XAOPLUGIN_EXPORT_AUTHOR</source>
      <translation>作成者</translation>
    </message>
    <message>
      <source>XAOPLUGIN_EXPORT_LGROUPS</source>
      <translation>グループ</translation>
    </message>
    <message>
      <source>XAOPLUGIN_EXPORT_LFIELDS</source>
      <translation>フィールド</translation>
    </message>
  </context>
  <context>
    <name>XAOPlugin_ImportDlg</name>
    <message>
      <source>XAOPLUGIN_IMPORT_TITLE</source>
      <translation>XAOインポート</translation>
    </message>
    <message>
      <source>XAOPLUGIN_IMPORTXAO</source>
      <translation>XAOインポート</translation>
    </message>
    <message>
      <source>XAOPLUGIN_IMPORT_INGSHAPE</source>
      <translation>オブジェクト</translation>
    </message>
    <message>
      <source>XAOPLUGIN_IMPORT_FILENAME</source>
      <translation>ファイル</translation>
    </message>
    <message>
      <source>XAOPLUGIN_IMPORT_LGROUPS</source>
      <translation>グループ</translation>
    </message>
    <message>
      <source>XAOPLUGIN_IMPORT_LFIELDS</source>
      <translation>フィールド</translation>
    </message>
    <message>
      <source>XAOPLUGIN_STEP</source>
      <translation>Step</translation>
    </message>
  </context>
</TS>
