// File generated by CPPExt (Value)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _NMTDS_BndSphere_HeaderFile
#define _NMTDS_BndSphere_HeaderFile

#ifndef _gp_Pnt_HeaderFile
#include <gp_Pnt.hxx>
#endif
#ifndef _Standard_Real_HeaderFile
#include <Standard_Real.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
class gp_Pnt;


#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif


class NMTDS_BndSphere  {

public:

    void* operator new(size_t,void* anAddress) 
      {
        return anAddress;
      }
    void* operator new(size_t size) 
      { 
        return Standard::Allocate(size); 
      }
    void  operator delete(void *anAddress) 
      { 
        if (anAddress) Standard::Free((Standard_Address&)anAddress); 
      }
 // Methods PUBLIC
 // 


Standard_EXPORT NMTDS_BndSphere();
Standard_EXPORT virtual ~NMTDS_BndSphere();

  void SetCenter(const gp_Pnt& theP) ;

 const gp_Pnt& Center() const;

  void SetRadius(const Standard_Real theR) ;

  Standard_Real Radius() const;

  void SetGap(const Standard_Real theGap) ;

  Standard_Real Gap() const;

  void Add(const NMTDS_BndSphere& theOther) ;


Standard_EXPORT   Standard_Boolean IsOut(const NMTDS_BndSphere& theOther) const;

  Standard_Real SquareExtent() const;





protected:

 // Methods PROTECTED
 // 


 // Fields PROTECTED
 //
gp_Pnt myCenter;
Standard_Real myRadius;
Standard_Real myGap;


private: 

 // Methods PRIVATE
 // 


 // Fields PRIVATE
 //


};


#include <NMTDS_BndSphere.lxx>



// other Inline functions and methods (like "C++: function call" methods)
//


#endif
