// File generated by CPPExt (Transient)
//
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _NMTDS_StdMapNodeOfMapOfPassKeyBoolean_HeaderFile
#define _NMTDS_StdMapNodeOfMapOfPassKeyBoolean_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Handle_NMTDS_StdMapNodeOfMapOfPassKeyBoolean_HeaderFile
#include <Handle_NMTDS_StdMapNodeOfMapOfPassKeyBoolean.hxx>
#endif

#ifndef _NMTDS_PassKeyBoolean_HeaderFile
#include <NMTDS_PassKeyBoolean.hxx>
#endif
#ifndef _TCollection_MapNode_HeaderFile
#include <TCollection_MapNode.hxx>
#endif
#ifndef _TCollection_MapNodePtr_HeaderFile
#include <TCollection_MapNodePtr.hxx>
#endif
class NMTDS_PassKeyBoolean;
class NMTDS_PassKeyMapHasher;
class NMTDS_MapOfPassKeyBoolean;
class NMTDS_MapIteratorOfMapOfPassKeyBoolean;



class NMTDS_StdMapNodeOfMapOfPassKeyBoolean : public TCollection_MapNode {

public:
 // Methods PUBLIC
 // 

NMTDS_StdMapNodeOfMapOfPassKeyBoolean(const NMTDS_PassKeyBoolean& K,const TCollection_MapNodePtr& n);

  NMTDS_PassKeyBoolean& Key() const;
//Standard_EXPORT ~NMTDS_StdMapNodeOfMapOfPassKeyBoolean();




 // Type management
 //
 Standard_EXPORT const Handle(Standard_Type)& DynamicType() const;
 //Standard_EXPORT Standard_Boolean	       IsKind(const Handle(Standard_Type)&) const;

protected:

 // Methods PROTECTED
 // 


 // Fields PROTECTED
 //


private: 

 // Methods PRIVATE
 // 


 // Fields PRIVATE
 //
NMTDS_PassKeyBoolean myKey;


};

#define TheKey NMTDS_PassKeyBoolean
#define TheKey_hxx <NMTDS_PassKeyBoolean.hxx>
#define Hasher NMTDS_PassKeyMapHasher
#define Hasher_hxx <NMTDS_PassKeyMapHasher.hxx>
#define TCollection_MapIterator NMTDS_MapIteratorOfMapOfPassKeyBoolean
#define TCollection_MapIterator_hxx <NMTDS_MapIteratorOfMapOfPassKeyBoolean.hxx>
#define TCollection_StdMapNode NMTDS_StdMapNodeOfMapOfPassKeyBoolean
#define TCollection_StdMapNode_hxx <NMTDS_StdMapNodeOfMapOfPassKeyBoolean.hxx>
#define Handle_TCollection_StdMapNode Handle_NMTDS_StdMapNodeOfMapOfPassKeyBoolean
#define TCollection_StdMapNode_Type_() NMTDS_StdMapNodeOfMapOfPassKeyBoolean_Type_()
#define TCollection_Map NMTDS_MapOfPassKeyBoolean
#define TCollection_Map_hxx <NMTDS_MapOfPassKeyBoolean.hxx>

#include <TCollection_StdMapNode.lxx>

#undef TheKey
#undef TheKey_hxx
#undef Hasher
#undef Hasher_hxx
#undef TCollection_MapIterator
#undef TCollection_MapIterator_hxx
#undef TCollection_StdMapNode
#undef TCollection_StdMapNode_hxx
#undef Handle_TCollection_StdMapNode
#undef TCollection_StdMapNode_Type_
#undef TCollection_Map
#undef TCollection_Map_hxx


// other Inline functions and methods (like "C++: function call" methods)
//


#endif
