<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="ja" sourcelanguage="en">
  <context>
    <name>DependencyTree_View</name>
    <message>
      <source>DEPENDENCY_TREE</source>
      <translation>依存関係ツリー</translation>
    </message>
    <message>
      <source>MOVE_NODES</source>
      <translation>ノードの移動</translation>
    </message>
    <message>
      <source>HIERARCHY_DEPTH</source>
      <translation>階層の深さ</translation>
    </message>
    <message>
      <source>DISPLAY_ASCENDANTS</source>
      <translation>上位の表示</translation>
    </message>
    <message>
      <source>DISPLAY_DESCENDANTS</source>
      <translation>下位の表示</translation>
    </message>
    <message>
      <source>SHOW_ALL</source>
      <translation>すべてを表示</translation>
    </message>
    <message>
      <source>UPDATE</source>
      <translation>更新</translation>
    </message>
    <name>DependencyTree_ViewModel</name>
    <message>
      <source>MEN_REBUILD_THE_TREE</source>
      <translation>ツリーの再構築</translation>
    </message>
    <message>
      <source>MEN_REDUCE_STUDY</source>
      <translation>スタディの削減</translation>
    </message>
  </context>
</TS>
