// File generated by CPPExt (Value)
//                     Copyright (C) 1991,1995 by
//  
//                      MATRA DATAVISION, FRANCE
//  
// This software is furnished in accordance with the terms and conditions
// of the contract and with the inclusion of the above copyright notice.
// This software or any other copy thereof may not be provided or otherwise
// be made available to any other person. No title to an ownership of the
// software is hereby transferred.
//  
// At the termination of the contract, the software and all copies of this
// software must be deleted.

#ifndef _NMTAlgo_Algo_HeaderFile
#define _NMTAlgo_Algo_HeaderFile

#ifndef _NMTTools_PDSFiller_HeaderFile
#include <NMTTools_PDSFiller.hxx>
#endif
#ifndef _TopoDS_Shape_HeaderFile
#include <TopoDS_Shape.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
class NMTTools_DSFiller;
class TopoDS_Shape;


#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

class NMTAlgo_Algo  {

public:

    void* operator new(size_t,void* anAddress) 
      {
        return anAddress;
      }
    void* operator new(size_t size) 
      { 
        return Standard::Allocate(size); 
      }
    void  operator delete(void *anAddress) 
      { 
        if (anAddress) Standard::Free((Standard_Address&)anAddress); 
      }
 // Methods PUBLIC
 // 
Standard_EXPORT   void SetFiller(const NMTTools_DSFiller& aDSF) ;
Standard_EXPORT  const NMTTools_DSFiller& Filler() const;
Standard_EXPORT virtual  void ComputeWithFiller(const NMTTools_DSFiller& aDSF) ;
Standard_EXPORT virtual  void Clear() ;
Standard_EXPORT  const TopoDS_Shape& Shape() const;
Standard_EXPORT   Standard_Boolean IsDone() const;
Standard_EXPORT   Standard_Integer ErrorStatus() const;





protected:

 // Methods PROTECTED
 // 
Standard_EXPORT NMTAlgo_Algo();
Standard_EXPORT virtual ~NMTAlgo_Algo();


 // Fields PROTECTED
 //
NMTTools_PDSFiller myDSFiller;
TopoDS_Shape myShape;
Standard_Boolean myIsDone;
Standard_Boolean myIsComputed;
Standard_Integer myErrorStatus;
Standard_Integer myDraw;


private: 

 // Methods PRIVATE
 // 


 // Fields PRIVATE
 //


};





// other Inline functions and methods (like "C++: function call" methods)
//


#endif
