// File generated by CPPExt (Value)
//                     Copyright (C) 1991,1995 by
//  
//                      MATRA DATAVISION, FRANCE
//  
// This software is furnished in accordance with the terms and conditions
// of the contract and with the inclusion of the above copyright notice.
// This software or any other copy thereof may not be provided or otherwise
// be made available to any other person. No title to an ownership of the
// software is hereby transferred.
//  
// At the termination of the contract, the software and all copies of this
// software must be deleted.

#ifndef _NMTAlgo_Splitter1_HeaderFile
#define _NMTAlgo_Splitter1_HeaderFile

#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
#ifndef _TopTools_DataMapOfShapeInteger_HeaderFile
#include <TopTools_DataMapOfShapeInteger.hxx>
#endif
#ifndef _TopoDS_Shape_HeaderFile
#include <TopoDS_Shape.hxx>
#endif
#ifndef _NMTAlgo_Splitter_HeaderFile
#include <NMTAlgo_Splitter.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _TopAbs_ShapeEnum_HeaderFile
#include <TopAbs_ShapeEnum.hxx>
#endif
class TopoDS_Shape;
class TopTools_DataMapOfShapeInteger;


#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

class NMTAlgo_Splitter1  : public NMTAlgo_Splitter {

public:

    void* operator new(size_t,void* anAddress) 
      {
        return anAddress;
      }
    void* operator new(size_t size) 
      { 
        return Standard::Allocate(size); 
      }
    void  operator delete(void *anAddress) 
      { 
        if (anAddress) Standard::Free((Standard_Address&)anAddress); 
      }
 // Methods PUBLIC
 // 
Standard_EXPORT NMTAlgo_Splitter1();
Standard_EXPORT virtual ~NMTAlgo_Splitter1();
Standard_EXPORT virtual  void Clear() ;
Standard_EXPORT virtual  void AddShape(const TopoDS_Shape& aS) ;
Standard_EXPORT virtual  void AddTool(const TopoDS_Shape& aS) ;
Standard_EXPORT   void SetMaterial(const TopoDS_Shape& aS,const Standard_Integer aM = 0) ;
Standard_EXPORT   void SetRemoveWebs(const Standard_Boolean bFlag) ;
Standard_EXPORT   Standard_Boolean RemoveWebs() const;
Standard_EXPORT  const TopTools_DataMapOfShapeInteger& GetMaterialTable() const;
Standard_EXPORT virtual  void Build(const TopAbs_ShapeEnum Limit = TopAbs_SHAPE) ;





protected:

 // Methods PROTECTED
 // 
Standard_EXPORT   void TreatSolids() ;
Standard_EXPORT   void TreatWebs() ;
Standard_EXPORT   void RestParts() ;


 // Fields PROTECTED
 //
Standard_Boolean myRemoveWebs;
TopTools_DataMapOfShapeInteger myMapSWM;
TopTools_DataMapOfShapeInteger myMapSWMOut;
TopoDS_Shape myRestParts;


private: 

 // Methods PRIVATE
 // 


 // Fields PRIVATE
 //


};





// other Inline functions and methods (like "C++: function call" methods)
//


#endif
