//  Copyright (C) 2003  OPEN CASCADE, EADS/CCR, LIP6, CEA/DEN,
//  CEDRAT, EDF R&D, LEG, PRINCIPIA R&D, BUREAU VERITAS 
// 
//  This library is free software; you can redistribute it and/or 
//  modify it under the terms of the GNU Lesser General Public 
//  License as published by the Free Software Foundation; either 
//  version 2.1 of the License. 
// 
//  This library is distributed in the hope that it will be useful, 
//  but WITHOUT ANY WARRANTY; without even the implied warranty of 
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU 
//  Lesser General Public License for more details. 
// 
//  You should have received a copy of the GNU Lesser General Public 
//  License along with this library; if not, write to the Free Software 
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA 
// 
//  See http://www.opencascade.org/SALOME/ or email : webmaster.salome@opencascade.org 
//
//
//
//  File   : GEOM_Shape.idl
//  Author : Lucien PIGNOLONI

#ifndef __GEOM_Shape__
#define __GEOM_Shape__

module GEOM
{
  //-----------------------------------------------------------------//
  //   Topological types for shapes (like Open Cascade types)        //
  //-----------------------------------------------------------------//
   
  enum shape_type { COMPOUND, COMPSOLID, SOLID, SHELL,
  		    FACE, WIRE, EDGE, VERTEX, SHAPE } ;
   
  //----------------------------------------------------------------//
  // Structures                                                     //
  //--------------------------------------------------- ------------//
  struct PointStruct { double x; 
  		       double y; 
  		       double z; } ; 
  struct DirStruct   { PointStruct PS ; } ;          // analog to Occ Direction
   
  struct AxisStruct  { double x;
  		       double y;
  		       double z;
  		       double vx;
  		       double vy;
  		       double vz; } ; 
   
  //----------------------------------------------------------------//
  // interface GEOM_Shape methods                                   //
  //----------------------------------------------------------------//

  interface GEOM_Gen;
  
  interface GEOM_Shape
  {
    typedef sequence<long>   ListOfSubShapeID ;
    typedef sequence<octet> TMPFile;
   
    attribute string Name;            // (to set and get) the name of shape (= CORBA IOR converted into a string)
    attribute string MainName;        // (to set and get) the name of mainshape (= CORBA IOR converted into a string)
   
    attribute boolean IsMainShape;    // (...) true if this is a main shape (not a sub shape)
    attribute string ShapeId;         // (...) the entry of the shape in geom/OCAF document
    attribute string StudyShapeId;    // (...) the entry of the shape in the study/OCAF when added
    attribute ListOfSubShapeID Index; // (...) list of references (number) identifing the sub shapes in the main shape
    attribute shape_type ShapeType;   // (...) a topological type of the shape
   
    attribute string NameType;        // (...) a topological/geometrical name of the shape
   
    //Transfer resulting shape to client as sequence of bytes
    //client can extract shape from stream using BrepTools::Read function
    TMPFile GetShapeStream();  	    
   
    // the generator engine
    GEOM_Gen Engine();
   
    // Get the TopoDS_Shape, for colocated case only
    long getShape();
  };
};
#endif
