// Copyright (C) 2014-2016  CEA/DEN, EDF R&D, OPEN CASCADE
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
//
// See http://www.salome-platform.org/ or email : webmaster.salome@opencascade.com
//

#ifndef __STEPPlugin_IDL__
#define __STEPPlugin_IDL__

#include "GEOM_Gen.idl"

module GEOM
{
  /*!
   *  \brief Units of length
   */
  enum length_unit
  {
    LU_INCH,
    LU_MILLIMETER,
    LU_FOOT,
    LU_MILE,
    LU_METER,
    LU_KILOMETER,
    LU_MILLIINCH,
    LU_MICROMETER,
    LU_CENTIMETER,
    LU_MICROINCH
  };

  /*!
   *  \brief Interface for STEPPlugin modeling functions.
   */
  interface ISTEPOperations : GEOM::GEOM_IOperations
  {
    /*!
     *  \brief Export the given shape into a file with given name in STEP format.
     *
     *  \param theObject Shape to be stored in the file.
     *  \param theFileName Name of the file to store the given shape in.
     *  \param theUnit the length unit.
     */
    void ExportSTEP( in GEOM::GEOM_Object theObject, 
                     in string            theFileName,
                     in GEOM::length_unit theUnit);
      
    /*!
     *  \brief Import a shape from the STEP file.
     *
     *  \param theFileName The file, containing the shape.
     *  \param theIsIgnoreUnits If True, file length units will be ignored (set to 'meter')
     *                          and result model will be scaled, if its units are not meters.
     *                          If False (default), file length units will be taken into account.
     *  \param IsCreateAssemblies If True, for each assembly compound is created
     *                          in the result. If False Compounds that contain a
     *                          single shape are eliminated from the result.
     *  \return List of GEOM_Objects, containing the created shape and propagation groups.
     */              
    GEOM::ListOfGO ImportSTEP( in string  theFileName,
                               in boolean theIsIgnoreUnits,
                               in boolean IsCreateAssemblies);
                               
    /*!
     *  \brief Read a value of parameter from a file, containing a shape.
     *  \param theFileName The file, containing the shape.
     *  \param theParameterName Specify the parameter. For example, pass "LEN_UNITS"
     *                          to obtain length units, in which the file is written.
     *  \return Value of requested parameter in form of text string.
     */
    string ReadValue( in string theFileName, 
                      in string theParameterName );
    
  };
};

#endif // __STEPPlugin_IDL__
