// Copyright (C) 2014-2016  CEA/DEN, EDF R&D, OPEN CASCADE
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
//
// See http://www.salome-platform.org/ or email : webmaster.salome@opencascade.com
//

#ifndef __VTKPlugin_IDL__
#define __VTKPlugin_IDL__

#include "GEOM_Gen.idl"

module GEOM
{
  /*!
   *  \brief Interface for VTKPlugin modeling functions.
   */
  interface IVTKOperations : GEOM::GEOM_IOperations
  {
    /*!
     *  \brief Export the given shape into a file with given name in VTK format.
     *
     *  \param theObject Shape to be stored in the file.
     *  \param theFileName Name of the file to store the given shape in.
     *  \param theDeflection Deflection of the given shape.
     */
    void ExportVTK( in GEOM::GEOM_Object theObject, 
                    in string            theFileName,
                    in double            theDeflection );
  };
};

#endif // __VTKPlugin_IDL__
