// File generated by CPPExt (Pointer)
//                     Copyright (C) 1991,1995 by
//  
//                      MATRA DATAVISION, FRANCE
//  
// This software is furnished in accordance with the terms and conditions
// of the contract and with the inclusion of the above copyright notice.
// This software or any other copy thereof may not be provided or otherwise
// be made available to any other person. No title to an ownership of the
// software is hereby transferred.
//  
// At the termination of the contract, the software and all copies of this
// software must be deleted.
//
#ifndef _NMTTools_PPaveFiller_HeaderFile
#define _NMTTools_PPaveFiller_HeaderFile

class NMTTools_PaveFiller;

typedef NMTTools_PaveFiller* NMTTools_PPaveFiller;

#endif
