// File generated by CPPExt (Value)
//                     Copyright (C) 1991,1995 by
//  
//                      MATRA DATAVISION, FRANCE
//  
// This software is furnished in accordance with the terms and conditions
// of the contract and with the inclusion of the above copyright notice.
// This software or any other copy thereof may not be provided or otherwise
// be made available to any other person. No title to an ownership of the
// software is hereby transferred.
//  
// At the termination of the contract, the software and all copies of this
// software must be deleted.
//
#include <NMTTools_CommonBlockPool.hxx>

#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _Standard_OutOfMemory_HeaderFile
#include <Standard_OutOfMemory.hxx>
#endif
#ifndef _NMTTools_ListOfCommonBlock_HeaderFile
#include <NMTTools_ListOfCommonBlock.hxx>
#endif
 

#define Array1Item NMTTools_ListOfCommonBlock
#define Array1Item_hxx <NMTTools_ListOfCommonBlock.hxx>
#define BOPTColStd_CArray1 NMTTools_CommonBlockPool
#define BOPTColStd_CArray1_hxx <NMTTools_CommonBlockPool.hxx>
#include <BOPTColStd_CArray1.gxx>

