// File generated by CPPExt (Value)
//                     Copyright (C) 1991,1995 by
//  
//                      MATRA DATAVISION, FRANCE
//  
// This software is furnished in accordance with the terms and conditions
// of the contract and with the inclusion of the above copyright notice.
// This software or any other copy thereof may not be provided or otherwise
// be made available to any other person. No title to an ownership of the
// software is hereby transferred.
//  
// At the termination of the contract, the software and all copies of this
// software must be deleted.

#ifndef _NMTTools_DSFiller_HeaderFile
#define _NMTTools_DSFiller_HeaderFile

#ifndef _TopoDS_Shape_HeaderFile
#include <TopoDS_Shape.hxx>
#endif
#ifndef _NMTDS_PShapesDataStructure_HeaderFile
#include <NMTDS_PShapesDataStructure.hxx>
#endif
#ifndef _BOPTools_PInterferencePool_HeaderFile
#include <BOPTools_PInterferencePool.hxx>
#endif
#ifndef _NMTTools_PPaveFiller_HeaderFile
#include <NMTTools_PPaveFiller.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
class TopoDS_Shape;
class NMTDS_ShapesDataStructure;
class BOPTools_InterferencePool;
class NMTTools_PaveFiller;


#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

class NMTTools_DSFiller  {

public:

    void* operator new(size_t,void* anAddress) 
      {
        return anAddress;
      }
    void* operator new(size_t size) 
      { 
        return Standard::Allocate(size); 
      }
    void  operator delete(void *anAddress) 
      { 
        if (anAddress) Standard::Free((Standard_Address&)anAddress); 
      }
 // Methods PUBLIC
 // 
Standard_EXPORT NMTTools_DSFiller();
Standard_EXPORT   void Destroy() ;
~NMTTools_DSFiller()
{
  Destroy();
}

Standard_EXPORT   void SetCompositeShape(const TopoDS_Shape& aS) ;
Standard_EXPORT  const TopoDS_Shape& CompositeShape() const;
Standard_EXPORT   void SetNewFiller(const Standard_Boolean aFlag) const;
Standard_EXPORT   Standard_Boolean IsNewFiller() const;
Standard_EXPORT   void Perform() ;
Standard_EXPORT  const NMTDS_ShapesDataStructure& DS() const;
Standard_EXPORT  const BOPTools_InterferencePool& InterfPool() const;
Standard_EXPORT   Standard_Boolean IsDone() const;
Standard_EXPORT  const NMTTools_PaveFiller& PaveFiller() const;
Standard_EXPORT   NMTTools_PaveFiller& ChangePaveFiller() ;





protected:

 // Methods PROTECTED
 // 
Standard_EXPORT   void Clear() ;


 // Fields PROTECTED
 //
TopoDS_Shape myCompositeShape;
NMTDS_PShapesDataStructure myDS;
BOPTools_PInterferencePool myInterfPool;
NMTTools_PPaveFiller myPaveFiller;
Standard_Boolean myIsDone;
Standard_Boolean myIsNewFiller;


private: 

 // Methods PRIVATE
 // 


 // Fields PRIVATE
 //


};





// other Inline functions and methods (like "C++: function call" methods)
//


#endif
