<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="ja" sourcelanguage="en">
  <context>
    <name>@default</name>
    <message>
      <source>MEN_EXPORTSTEP</source>
      <translation>STEPエクスポート</translation>
    </message>
    <message>
      <source>TOP_EXPORTSTEP</source>
      <translation>STEPエクスポート</translation>
    </message>
    <message>
      <source>STB_EXPORTSTEP</source>
      <translation>STEPエクスポート</translation>
    </message>
    <message>
      <source>MEN_IMPORTSTEP</source>
      <translation>STEPインポート</translation>
    </message>
    <message>
      <source>TOP_IMPORTSTEP</source>
      <translation>STEPインポート</translation>
    </message>
    <message>
      <source>STB_IMPORTSTEP</source>
      <translation>STEPインポート</translation>
    </message>
  </context>
  <context>
    <name>STEPPlugin_GUI</name>
    <message>
      <source>STEP_FILES</source>
      <translation>STEPファイル</translation>
    </message>
    <message>
      <source>EXPORT_TITLE</source>
      <translation>STEPエクスポート</translation>
    </message>
    <message>
      <source>IMPORT_TITLE</source>
      <translation>STEPインポート</translation>
    </message>
    <message>
      <source>SCALE_DIMENSIONS</source>
      <translation>インポートしたファイルの単位をミリメートルからメートルに変換しますか？いいえを選んだ場合、メートル単位として解釈します。</translation>
    </message>
  </context>
</TS>
