<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="ja" sourcelanguage="en">
  <context>
    <name>@default</name>
    <message>
      <source>MEN_EXPORTSTEP</source>
      <translation>STEPエクスポート</translation>
    </message>
    <message>
      <source>TOP_EXPORTSTEP</source>
      <translation>STEPエクスポート</translation>
    </message>
    <message>
      <source>STB_EXPORTSTEP</source>
      <translation>STEPエクスポート</translation>
    </message>
    <message>
      <source>MEN_IMPORTSTEP</source>
      <translation>STEPインポート</translation>
    </message>
    <message>
      <source>TOP_IMPORTSTEP</source>
      <translation>STEPインポート</translation>
    </message>
    <message>
      <source>STB_IMPORTSTEP</source>
      <translation>STEPインポート</translation>
    </message>
  </context>
  <context>
    <name>STEPPlugin_GUI</name>
    <message>
      <source>STEP_FILES</source>
      <translation>STEP ファイル ( *.step *.stp )</translation>
    </message>
    <message>
      <source>EXPORT_TITLE</source>
      <translation>STEPエクスポート</translation>
    </message>
    <message>
      <source>IMPORT_TITLE</source>
      <translation>STEPインポート</translation>
    </message>
    <message>
      <source>SCALE_DIMENSIONS</source>
      <translation>インポートしたファイルの単位をミリメートルからメートルに変換しますか？いいえを選んだ場合、メートル単位として解釈します。</translation>
    </message>
  </context>
  <context>
    <name>STEPPlugin_ExportDlg</name>
    <message>
      <source>STEP_LENGTH_UNITS</source>
      <translation>長さの単位</translation>
    </message>
    <message>
      <source>STEP_UNITS_INCH</source>
      <translation>インチ</translation>
    </message>
    <message>
      <source>STEP_UNITS_MILLIMETER</source>
      <translation>ミリメートル</translation>
    </message>
    <message>
      <source>STEP_UNITS_FOOT</source>
      <translation>フィート</translation>
    </message>
    <message>
      <source>STEP_UNITS_MILE</source>
      <translation>マイル</translation>
    </message>
    <message>
      <source>STEP_UNITS_METER</source>
      <translation>メートル</translation>
    </message>
    <message>
      <source>STEP_UNITS_KILOMETER</source>
      <translation>キロメートル</translation>
    </message>
    <message>
      <source>STEP_UNITS_MILLIINCH</source>
      <translation>ミリインチ</translation>
    </message>
    <message>
      <source>STEP_UNITS_MICROMETER</source>
      <translation>マイクロメートル</translation>
    </message>
    <message>
      <source>STEP_UNITS_CENTIMETER</source>
      <translation>センチメートル</translation>
    </message>
    <message>
      <source>STEP_UNITS_MICROINCH</source>
      <translation>マイクロインチ</translation>
    </message>
  </context>
  <context>
    <name>STEPPlugin_ImportDlg</name>
    <message>
      <source>STEP_CREATE_ASSEMBLIES</source>
      <translation>アセンブリの作成</translation>
    </message>
  </context>
</TS>
